language: php

php:
  - 7.0.8

before_install:
  - phpenv config-rm xdebug.ini || true
  
install:
  - cd web
  - composer install
  - cd core
  
script: ../vendor/bin/phpunit --testsuite=unit 

notifications:
  email: false
  slack: ldso-italien:Q0U7sHHaNrawf6UVsV2J58A9

branches:
  only:
  - master
  - develop
